export const catalogListings = [
  {
    id: "1",
    slug: "cement-m500-optom",
    title: "Цемент М500 оптом",
    price: "320",
    unit: "мешок",
    moq: "100",
    seller: "СтройОпт КР",
    city: "Бишкек",
    category: "Строительные материалы",
    verified: true,
  },
  {
    id: "2",
    slug: "ris-krasniy-25kg",
    title: "Рис красный 25 кг",
    price: "1 850",
    unit: "мешок",
    moq: "20",
    seller: "АзияФуд",
    city: "Бишкек",
    category: "Продукты питания",
    verified: true,
  },
  {
    id: "3",
    slug: "perchatki-nitril",
    title: "Перчатки нитриловые",
    price: "45",
    unit: "уп.",
    moq: "500",
    seller: "МедСнаб",
    city: "Ош",
    category: "Хозтовары",
    verified: false,
  },
  {
    id: "4",
    slug: "kartonnye-korobki",
    title: "Картонные коробки",
    price: "28",
    unit: "шт.",
    moq: "1 000",
    seller: "УпакПлюс",
    city: "Бишкек",
    category: "Упаковка",
    verified: true,
  },
  {
    id: "5",
    slug: "maslo-podsolnechnoe",
    title: "Масло подсолнечное 5 л",
    price: "420",
    unit: "канистра",
    moq: "50",
    seller: "АзияФуд",
    city: "Бишкек",
    category: "Продукты питания",
    verified: true,
  },
  {
    id: "6",
    slug: "kraska-fasadnaya",
    title: "Краска фасадная 20 кг",
    price: "2 100",
    unit: "ведро",
    moq: "10",
    seller: "СтройОпт КР",
    city: "Бишкек",
    category: "Строительные материалы",
    verified: true,
  },
];

export const categoryList = [
  {
    id: "1",
    name: "Продукты питания",
    slug: "produkty-pitaniya",
    count: 124,
    icon: "🥫",
  },
  {
    id: "2",
    name: "Строительные материалы",
    slug: "stroitelnye-materialy",
    count: 89,
    icon: "🧱",
  },
  {
    id: "3",
    name: "Одежда оптом",
    slug: "odezhda-optom",
    count: 56,
    icon: "👔",
  },
  {
    id: "4",
    name: "Электроника",
    slug: "elektronika",
    count: 42,
    icon: "💡",
  },
  {
    id: "5",
    name: "Хозтовары",
    slug: "hoztovary",
    count: 73,
    icon: "🧴",
  },
  {
    id: "6",
    name: "Автотовары",
    slug: "avtotovary",
    count: 31,
    icon: "🚗",
  },
  {
    id: "7",
    name: "Мебель",
    slug: "mebel",
    count: 28,
    icon: "🪑",
  },
  {
    id: "8",
    name: "Канцтовары",
    slug: "kantovary",
    count: 19,
    icon: "📎",
  },
];

export const sellerList = [
  {
    id: "1",
    slug: "stroyopt-kr",
    name: "СтройОпт КР",
    city: "Бишкек",
    listingsCount: 24,
    verified: true,
    description: "Оптовые поставки строительных материалов по Кыргызстану.",
  },
  {
    id: "2",
    slug: "aziyafud",
    name: "АзияФуд",
    city: "Бишкек",
    listingsCount: 18,
    verified: true,
    description: "Продукты питания и бакалея для магазинов и HoReCa.",
  },
  {
    id: "3",
    slug: "medsnab",
    name: "МедСнаб",
    city: "Ош",
    listingsCount: 12,
    verified: false,
    description: "Расходные материалы и средства защиты для бизнеса.",
  },
  {
    id: "4",
    slug: "upakplyus",
    name: "УпакПлюс",
    city: "Бишкек",
    listingsCount: 9,
    verified: true,
    description: "Упаковочные материалы оптом от производителя.",
  },
];

export const categoryOptions = categoryList.map((c) => ({
  value: c.slug,
  label: c.name,
}));

export const cityOptions = ["Бишкек", "Ош", "Каракол", "Джалал-Абад", "Токмок", "Кант"];
